name: Build Orange Pi Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Build Orange Pi image
        run: |
          packer build html_email_editor/packer/packer.pkr.hcl

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: orange-pi-image
          path: html_email_editor/packer/output-image/
